-- CREAR USUARIO NUEVO CON CONTRASEÑA --
-- CREAMOS EL NOMBRE DE USUARIO QUE QUERAMOS --
CREATE USER 
'saas'@'localhost' 
IDENTIFIED  BY 'Saas2526$';

-- PERMITIR ACCESO AL USUARIO --
GRANT USAGE ON *.* TO 'saas'@'localhost';

-- SACARLE TODAS LAS RESTRICCIONES --
ALTER USER 'saas'@'localhost'
REQUIRE NONE 
WITH MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 
MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0;

-- DAR ACCESO A LA BBDD "[]" --
GRANT ALL PRIVILEGES ON `appsaas`.* 
TO 'saas'@'localhost';

-- RECARGAR LA TABLA DE PRIVILEGIOS --
FLUSH PRIVILEGES;
